### ISSUE TITLE
User can turn their car.

### ISSUE THREAD

**Issue by Jazzmine-Jimenez** [Jazzmine-Jimenez/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] listen for keyboard event for arrows
- [x] make car direction match arrow direction within keyboard event using transform.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again.
