### ISSUE TITLE
User can start their car.

### ISSUE THREAD

**Issue by Jazzmine-Jimenez** [Jazzmine-Jimenez/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Add a location to data model to hold x & y coordinates
- [x] Add event listener to start car when space bar is pushed
- [x] Set positioning of image to absolute 
- [x] Use the style property to change car's top & left box offset styles
- [x] Add a setInterval() to move the car for every 16 milliseconds
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again.
