### ISSUE TITLE
User can stop their car.

### ISSUE THREAD

**Issue by Jazzmine-Jimenez** [Jazzmine-Jimenez/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] Add a boolean property to data model 
- [x] When spacebar is pushed start  or stop car depending on boolean value 
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again.
