### ISSUE TITLE
User can steer their car.

### ISSUE THREAD

**Issue by Jazzmine-Jimenez** [Jazzmine-Jimenez/driving-game#5]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] Within keyboard event have the car stop when an arrow is pressed if the car moving
- [x] Within keyboard event have the car change direction in x values when corresponding arrow is pushed (left/right or west/east)
- [x] Within keyboard event have the car change direction in y values when corresponding arrow is pushed (up/down or north/south)
- [x] Within keyboard event have the car change direction either x or y values when corresponding arrow is pushed
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x]  Test all functionality again.
